server:
  port: 8080
spring:
  application:
    name: client-a
eureka:
  client:
    serviceUrl:
      #defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
      defaultZone: http://${eureka.host:localhost}:${eureka.port:1111}/eureka/
  instance:
    prefer-ip-address: true
