spring:
  application:
    name: zuul-server
server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:1111}/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: client-a